language: node_js
cache:
  directories:
    - node_modules
git:
  submodules: false
env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2
node_js:
  - '10'
install: true
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm install -g cfn-lint
script:
  - cfn-lint validate templates/bastion.yaml
  - cfn-lint validate templates/ghost.yaml
  - cfn-lint validate templates/rds.yaml
  - cfn-lint validate templates/vpc.yaml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation templates validated"

notifications:
  email: false
