language: ruby

git:
  submodules: false

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2

before_install:
  - npm install -g cfn-lint

install: true

script:
  - cfn-lint validate templates/bastion.yaml
  - cfn-lint validate templates/ghost.yaml
  - cfn-lint validate templates/rds.yaml
  - cfn-lint validate templates/vpc.yaml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation templates validated"

notifications:
  email: false
