language: node_js
cache:
  directories:
    - node_modules
git:
  submodules: false
env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2
node_js:
  - '10'
install: true
before_script:
  - npm install -g cfn-lint
script:
  - cfn-lint validate --verbose --pseudo AWS::Region=ap-southeast-2 templates/bastion.yaml
  - cfn-lint validate --verbose --pseudo AWS::Region=ap-southeast-2 templates/ghost.yaml
  - cfn-lint validate --verbose --pseudo AWS::Region=ap-southeast-2 templates/rds.yaml
  - cfn-lint validate --verbose --pseudo AWS::Region=ap-southeast-2 templates/vpc.yaml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation templates validated"

notifications:
  email: false
